services:
  webex-tts-frontend:
    image: ghcr.io/sieteunoseis/webex-tts-frontend:main
    container_name: webex-tts-frontend
    ports:
      - "3000:80" # Map port 3000 on host to port 80 in container
    networks:
      - webex-network
    env_file:
      - frontend.env

  webex-tts-backend:
    image: ghcr.io/sieteunoseis/webex-tts-backend:main
    container_name: webex-tts-backend
    volumes:
      - ./data:/usr/src/app/data
    expose:
      - "5000"
    user: "${UID:-1000}:${GID:-1000}"  # Use host user's UID/GID
    networks:
      - webex-network
    env_file:
      - backend.env

networks:
  webex-network:
    driver: bridge